# Generated by Django 2.0.6 on 2019-04-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelType', models.CharField(max_length=50)),
                ('DID', models.CharField(max_length=30)),
                ('DType', models.CharField(max_length=30)),
                ('SysVersion', models.CharField(max_length=50)),
            ],
        ),
    ]
