# Generated by Django 2.0.6 on 2019-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0002_mobileborrowingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='BorrowStatus',
            field=models.BooleanField(default=True),
        ),
    ]
