# Generated by Django 2.0.6 on 2019-04-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0003_mobile_borrowstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileMd5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.IntegerField()),
                ('md5', models.CharField(max_length=100)),
                ('creatTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='mobileborrowingrecord',
            name='BorrowTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='mobileborrowingrecord',
            name='ReturnTime',
            field=models.DateTimeField(),
        ),
    ]
