# Generated by Django 2.0.6 on 2019-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0004_auto_20190404_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilemd5',
            name='creatTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mobilemd5',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
