# Generated by Django 2.0.6 on 2019-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0005_auto_20190404_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('identity', models.IntegerField(default=1)),
                ('u_token', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mobile',
            name='BorrowPeopleID',
            field=models.IntegerField(default=None),
        ),
    ]
