# Generated by Django 2.0.6 on 2019-04-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0006_auto_20190409_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='BorrowPeopleID',
            field=models.IntegerField(default=0),
        ),
    ]
