# Generated by Django 2.0.6 on 2019-04-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0011_auto_20190409_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creatTime',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='updateTime',
            field=models.DateField(auto_now=True),
        ),
    ]
