# Generated by Django 2.0.6 on 2019-04-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0012_auto_20190409_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='creatTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_token',
            field=models.CharField(default='notoken', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
