# Generated by Django 2.0.6 on 2019-04-09 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0013_auto_20190409_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=60, unique=True),
        ),
    ]
