# Generated by Django 2.0.6 on 2019-04-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0014_auto_20190409_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileborrowingrecord',
            name='BorrowTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mobileborrowingrecord',
            name='ReturnTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
