# Generated by Django 2.0.6 on 2019-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0015_auto_20190410_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='BorrowPeopleName',
            field=models.CharField(default='None', max_length=60),
        ),
    ]
