# Generated by Django 2.0.6 on 2019-06-26 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0016_mobile_borrowpeoplename'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileApplicationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('status', models.IntegerField()),
                ('creatTime', models.DateTimeField(auto_now_add=True)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
