# Generated by Django 2.0.6 on 2019-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0017_mobileapplicationrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='applyUserid',
            field=models.IntegerField(default=0),
        ),
    ]
