# Generated by Django 2.0.6 on 2019-06-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0018_mobile_applyuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='applyUserName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
