# Generated by Django 2.0.6 on 2019-07-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobiles', '0019_mobile_applyusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='salt',
            field=models.IntegerField(default=0),
        ),
    ]
